const HANDLER_NAME_PATTERN = /^(on)(.+)(Handler)$/i

const WRONG_HANDLER_NAME_MESSAGE = 'Handler should starts with "on" and ends with "Handler"'

const SHARED_HANDLERS = {
    "AbTestsTable": ["onToggleBar"],
    "ActionButtons": ["onHideDeleteModalHandler", "onHideEditModalHandler", "onShowDeleteClickHandler", "onShowEditModalHandler"],
    "ActionTypeBlock": ["onActionChange"],
    "AddEmailForm": ["handleFormSubmitted", "onChangeIsMainHandler", "onConfirmNewMailHandler", "onCopyAddressHandler", "onCopyLinkHandler", "onCopyPasswordHandler", "onOpenChangeTutorialModalHandler", "onOpenChangeTutorialNotGmailModalHandler", "openTutorialModalHandler", "setToolTipAddressOpen", "setToolTipPasswordOpen"],
    "AddGeoForm": ["onAddGeosHandler"],
    "AddGeoModal": ["onOpenChangeHandler"],
    "AddKeyForm": ["handleFormSubmitted"],
    "AddKeywordsForm": ["onAddGeosHandler", "onRepeatQueryAsoMobileAppsHandler"],
    "AddKeywordsFromAppBlock": ["onAddKeywordsHandler", "onChangeIsSelectAppsHandler"],
    "AddKeywordsModal": ["onClearInputHandler", "onCloseSelectAppsModalHandler", "onOpenChangeHandler"],
    "AddValueForm": ["onChangeStepHandler", "onCreateValueHandler"],
    "AddingCommentBlock": ["addComment", "handleEditComment"],
    "AddKeysToNiche": ["handleFormSubmitted", "onChangeAction", "onRepeatRequestHandler"],
    "addValueBlock": ["handleHideAddModal", "handleShowAddModal", "onClickButtonWhenModalOpen"],
    "AdvertisingTableActionsCell": ["onAddAdsHandler", "onDeleteAdsHandler", "onOpenChangeAddHandler", "onOpenChangeEditHandler", "onSaveAdsHandler", "setOpenAdd", "setOpenDelete", "setOpenEdit"],
    "Alert": ["closeToast"],
    "AppAdvertisingForm": ["handleFormSubmitted"],
    "AppAdvertisingTable": ["onChangePerPageHandler", "onSetCurrentPageHandler", "onToggleBar"],
    "AppCard": ["onClickAppLinkHandler"],
    "AppEmails": ["onChangeMainMailsModalsHandler", "onChangeNewMailsModalsHandler"],
    "AppItem": ["onClickRemoveHandler", "onToogleCheckboxHandler"],
    "AppListActionBlock": ["onOpenChangeModalAddKeysHandler", "setOpenAddKeys"],
    "AppListModal": ["onAddToGroupHandler"],
    "AppModal": ["onChangeHandler", "onRemoveIsAddToNicheHandler"],
    "AppTitle": ["onClickLinkHandler"],
    "AppleAppFilters": ["onChangeFiltersHandler", "onResetAllFiltersHandler", "onResetFilterHandler", "setIsOpenFilterSelect"],
    "AsoMobileForm": ["handleFormSubmitted", "onChangeCountryValueHandler", "onChangeNicheId", "onRepeatRequestHandler"],
    "Attribute": ["onClickAttrHandler", "onClickCloseButtonHandler", "onOpenChangSecondTooltipHandler"],
    "BasicFormPush": ["handleAppChange", "handleNicheChange"],
    "Breadcrumbs": ["handleDropDownOpenChange", "handleDropDownValueChange"],
    "Card": ["onClickAppLinkHandler", "onClickCardHandler", "onClickDashboardLinkHandler"],
    "CardMetricPush": ["onClickActionButtonHandler", "onClickSecondButtonHandler"],
    "ChangeMainEmailForm": ["onClickSaveButtonHandler", "setSearchValueHandler"],
    "ChangeStatusForm": ["onChangeStatus", "onSaveHandler"],
    "ChartBlock": ["onRepeatRequestHandler"],
    "CheckItem": ["onChangeTrackingCheckHandler", "onOpenChangeTrackModalHandler"],
    "CheckTable": ["onChangeOpenTableHandler", "onChangeTrackingCheckHandler", "onCloseDeleteModalHandler", "onDeleteCheckHandler", "onOpenDeleteModalHandler", "onSetSortHandler", "setOpenPopup"],
    "ChecksFilters": ["onApplyDatesHandler", "onChangeDaysHandler", "onChangeSearchHandler", "onClearInputHandler", "onCloseCalendarHandler", "onOpenCalendarHandler", "onResetDateToDefaultHandler", "onSetStartDateHandler", "onStateFilterChangeHandler"],
    "Collapsible": ["handleOpenChanged"],
    "CommentModal": ["openCommentAddingModal", "openCommentEditingModal", "setIsCommentAddingModalOpen", "setIsCommentEditingModalOpen", "setIsCommentModalOpen"],
    "CommentTableModal": ["setOpenComment"],
    "ContentBlock": ["onCloseSliderModalHandler", "toggleShowAllHandler"],
    "ContentForm": ["addExternalFiles", "deleteExternalFiles", "onChangeImgVarHandler", "onReorderFilesHandler"],
    "ContentFormList": ["addNewVariantHandler"],
    "ContentImgUpload": ["addExternalFiles", "deleteExternalFiles", "onReorderFilesHandler"],
    "CustomHeader": ["onChangeMonthHandler", "onChangeYearHandler", "onClickMonth", "onClickYear", "onDecreasePeriodHandler", "onEndDateBlurHandler", "onEndDateChangeHandler", "onIncreasePeriodHandler", "onKeyEndDateHandler", "onKeyStartDateHandler", "onResetDateStartHandler", "onStartDateBlurHandler", "onStartDateChangeHandler"],
    "DateInput": ["onBlurInputHandler", "onCloseCalendarHandler", "onKeyDownInputHandler", "onOpenCalendarHandler"],
    "DatePickerComp": ["datePickerHandler", "onClickMonthHandler", "onClickOutsideHandler", "onClickYearHandler"],
    "DeleteItem": ["handleFormSubmitted", "onSubmitHandler"],
    "DeleteModal": ["hadleCancel", "handleDelete", "setIsDeleteModalOpen"],
    "DeleteValueForm": ["onDeleteHandler", "setDeleteValueModalOpen"],
    "DetailedStat": ["onChangePerPageHandler", "onClickLinkHandler", "onFilterChangeHandler", "onScrollHandler", "onSetCurrentPageHandler", "onSetSortHandler"],
    "DetailedStatChart": ["onApplyDatesHandler", "onChangeDaysHandler", "onCloseCalendarHandler", "onOpenCalendarHandler", "onResetDateToDefaultHandler", "onSetEndDateHandler", "onSetStartDateHandler", "setAppChartDataType", "setChartAppModalParam"],
    "DonutBar": ["onMouseEnterHandler", "onMouseLeaveHandler", "onMouseMoveHandler"],
    "DynamicIndicatorsBlock": ["setCurrentTab"],
    "EditableCell": ["clickEditBtnHandler", "setOpenEditModal"],
    "EditInstallsForm": ["onSaveHandler"],
    "EditKeys": ["onAddNewCheckKeyHandler", "onChangeModalDisplayHandler", "onRepeatRequestHandler"],
    "EditKeywords": ["onAddToGeoKeywordsHandler", "onChangeValueHandler", "onUpdateNicheHandler"],
    "EditKeywordsPush": ["onAddKeywordHandler", "onChangeInputValue", "onDeleteKeywordHandler", "onKeywordExistModalCloseHandler", "onUpdateKeywordsHandler"],
    "EditLinksBlock": ["handleSaveLinks"],
    "EditParamForm": ["onGnrlParamKeyChangeHandler", "onRepeatRequestHandler", "onSaveParametersHandler", "onStffParamChangeHandler"],
    "EditUndefinedValueForm": ["onChangeSearchHandler", "onClearInputHandler", "onRepeatRequestHandler"],
    "EditValueForm": ["onChangePointsHandler", "onChangePointsTypeHandler", "onSaveHandler"],
    "EditingCommentBlock": ["changeComment", "handleEditComment"],
    "EmailItem": ["onClickEmailHandler", "onToogleMainMail"],
    "EmailTutorial": ["setTutorialModalDisplay"],
    "EmployeesTable": ["handleSortChange", "onClickLinkHandler", "setSearch"],
    "FileUpload": ["onDrop"],
    "FilesFrame": ["onImageDragEndHandler"],
    "Filter": ["onOpenChangeHandler", "onParamTypeChangeHandler"],
    "FinalForm": ["onEditInstallsHandler"],
    "HeaderActions": ["onAddGeoHandler", "onAddKeywordsHandler", "onClickAddGeoHandler", "onClickAddKeywrodsHandler", "setIsOpenAddGeoModal", "setIsOpenAddKeywordsModal"],
    "HistoryScoreChangesTable": ["handleSortChange", "onChangeConsiderStatusHandler", "onChangePerPageHandler", "onChangeSearchHandler", "onClearInputHandler", "onCreateScoreNoteHandler", "onOpenChangeAddPointsHandler", "onSetCurrentPageHandler", "onToggleBar", "setOpenAddPoints"],
    "HistoryScoreTableActionsCell": ["onOpenChangeEditHandler", "onUpdateScoreHandler", "setOpenEdit", "setOpenReturn", "setOpenRevoke"],
    "Image": ["imageLoadHandler"],
    "ImageContainer": ["onDelete"],
    "Input": ["handleChange", "handleClearInput", "handleToggleShowPassword"],
    "InstallationsTableRow": ["updateTaskHandler"],
    "Keyword": ["onSetIsDeletedHandler"],
    "KeywordActions": ["handleDeleteModalClose", "handleEditModalClose", "onClickDeleteBtnHandler", "onClickEditBtnHandler", "onClickSaveEditKeywords", "onDeleteHandler"],
    "KeywordInstallsTable": ["handleDeleteModalClose", "handleDeleteSelected", "handleKeepModalClose", "handleKeepSelected", "handleSelectAll", "onClickDeleteHandler", "onClickKeepHandler", "onScrollHandler", "onToggleBar"],
    "KeywordPush": ["onDeletedHandler"],
    "KeywordsForm": ["handleDeleteAllCheckboxChange", "handleDeleteModalClose", "handleDeleteSelectedGeos", "onClickDeleteGeosHandler"],
    "KeywordsTableRow": ["handleDeleteModalClose", "handleKeepModalClose", "onClickDeleteHandler", "onClickKeepHandler"],
    "Letter": ["onChangeFavouriteLetterHandler", "onDeleteLetterHandler", "onReturnToLettersHandler"],
    "LetterImage": ["setOpenImageModal"],
    "LetterItem": ["onChangeFavouriteLetterHandler", "onChangeReadLetterHandler", "onDeleteLetterHandler", "onOpenLetterHandler", "setIsHoveredLetter"],
    "Letters": ["onDeleteAllLettersHandler", "onReadAllLettersHandler", "setOpenDeleteAllLettersModal", "setOpenPopup"],
    "LinkParamList": ["onChangeSearchHandler", "onClearInputHandler", "onRadioChangeHandler", "onSumbitFormHandler"],
    "ListOfApplicationsTable": ["onFilterChangeHandler", "onToggleBar"],
    "ListOfInstallationsTable": ["onToggleBar", "updateTasksHandler"],
    "LogIn": ["handleFormSubmitted", "onChangeHandler", "setOpen"],
    "MetricCard": ["onChangeChartAppParamHandler", "onChangeShowDetailsHandler"],
    "Modal": ["onClickActionButtonHandler"],
    "MultiSelect": ["fetchNextPageHandler", "onChangeSearchHandler", "onClearInputHandler", "onClickCloseAllOptions", "preventListboxKeyDownHandler"],
    "Navbar": ["openNotificationHandler", "openSubMenuHandler"],
    "NicheActionsCell": ["onCopyClickHandler", "onEditKeywordsHandler", "onGeoDeleteHandler", "onOpenChangeDeleteHandler", "onOpenChangeEditHandler", "setOpenDelete", "setOpenEdit"],
    "NicheAppList": ["onChangeAddAllKeysHandler", "onChangePerPageHandler", "onChangeSearchHandler", "onClearInputHandler", "onOpenChangeModalAddGroupKeysHandler", "onRepeatRequestHandler", "onSetCurrentPageHandler", "setOpenAddGroupKeys"],
    "NicheAppListModal": ["onAddToNicheGroupHandler"],
    "NicheForm": ["handleFormSubmitted", "onChangeAction", "onChangeIsSelectAppsHandler", "onRepeatRequestHandler"],
    "NicheList": ["onChangePerPageHandler", "onChangeSearchHandler", "onClearInputHandler", "onRepeatRequestHandler", "onSetCurrentPageHandler", "onSetSortHandler"],
    "NicheTable": ["onChangeDeleteAllGeosHandler", "onChangeDeleteGeoHandler", "onChangePerPageHandler", "onChangeSearchHandler", "onClearInputHandler", "onGroupCopyClickHandler", "onGroupGeosDeleteHandler", "onOpenChangeModalDeleteAllGeosHandler", "onSetCurrentPageHandler", "onSetSortHandler", "setOpenDelete"],
    "NicheTitle": ["onChangeSearchHandler", "onClearInputHandler", "onCloseSelectAppsModalHandler", "onDeleteNicheHandler", "onOpenChangeAddKeysModalHandler", "onOpenChangeDeleteHandler", "onOpenChangeUpdateNameHandler", "onScrollHandler", "onUpdateNicheNameHandler", "setOpenAddKeys", "setOpenDelete", "setOpenPopup", "setOpenUpdate"],
    "NoCommentsBlock": ["openCommentAddingModal"],
    "Notification": ["onClickLinkHandler", "setIsReadNewNotifHandler"],
    "NotificationsList": ["onMarkAllNotificationAsReadHandler", "onRepeatRequestHandler", "onScrollHandler", "onScrollToTopHandler", "setOpenPopup"],
    "OtherScreens": ["onToggleOpenOtherScreensHandler"],
    "OutKeywordsFilters": ["onChangeFiltersHandler", "onChangeFilterValuesHandler", "onResetAllFiltersHandler", "onResetFilterHandler", "setIsOpenFilter", "setIsOpenFilterSelect"],
    "OutKeywordsTable": ["handleDeleteOutKeywords", "handleKeepOutKeywords", "onToggleBar"],
    "OutKeywordsTableWrapped": ["onToggleBar"],
    "ParamAppListModal": ["onAddToParamKeyAppGroupHandler"],
    "ParamAppModal": ["onApplyActionToAppHandler", "onChangeHandler", "onUnlinkAppModalHandler", "setOpenUnlinkAppModal"],
    "ParamKeyForm": ["handleFormSubmitted", "onChangeIsSelectAppsHandler"],
    "Parameters": ["onChangeOpenChartModalHandler"],
    "ParamsForm": ["onGnrlParamKeyChangeHandler"],
    "PointsBlock": ["onPointsTypeChange"],
    "PushBotsFilters": ["onChangeFiltersHandler", "onChangeFilterValuesHandler", "onResetAllFiltersHandler", "onResetFilterHandler", "setIsOpenFilter", "setIsOpenFilterSelect"],
    "Rating": ["handleClick", "handleHover"],
    "RatingPrimitive": ["onMouseLeave", "symbolClick", "symbolEnd", "symbolMouseMove"],
    "RatingsTable": ["onChangePerPageHandler", "onChangeSearchHandler", "onClearInputHandler", "onRepeatRequestHandler", "onSetCurrentPageHandler", "onSetSortHandler"],
    "RefreshButton": ["onStartRefreshMode"],
    "RenameTestVarName": ["handleFormSubmitted"],
    "ReviewRow": ["onToggleOpenHandler"],
    "ReviewsTable": ["onApplyDatesHandler", "onChangeAppsValueHandler", "onChangeCountryValueHandler", "onChangeDaysHandler", "onChangePerPageHandler", "onChangeRatingValueHandler", "onChangeSearchHandler", "onClearInputHandler", "onCloseCalendarHandler", "onOpenCalendarHandler", "onRepeatRequestHandler", "onResetDateToDefaultHandler", "onSetCurrentPageHandler", "onSetEndDateHandler", "onSetSortHandler", "onSetStartDateHandler", "onShowRealDataChangeHandler", "onTranslateAllChangeHandler"],
    "SawCommentBlock": ["openCommentEditingModal"],
    "SawLinksBlock": ["openLinksEditingModalOpen"],
    "ScoreChangesForm": ["handleFormSubmitted"],
    "Screenshots": ["onClickImageHandler", "onCloseSliderModalHandler", "toggleShowAllHandler"],
    "Select": ["onBlurHandler", "onChangeSearchHandler", "onClearInputHandler"],
    "SelectNewApps": ["onChangeNewAppsHandler"],
    "SignUp": ["handleFormSubmitted"],
    "Slider": ["onClickSliderHandler"],
    "StaffForm": ["onStffParamChangeHandler"],
    "StepWrapper": ["onDeleteTestVariantHandler", "onRenameTestVarNameHandler"],
    "StepsNavigator": ["onClickNextButtonHandler", "onClickPrevButtonHandler"],
    "StrategyForm": ["handleStrategyChange", "handleStrategyIsNotInListChange"],
    "TabDaysApps": ["onApplyDatesHandler", "onChangeDaysAppsHandler", "onCloseCalendarHandler", "onOpenCalendarHandler", "onResetDateToDefaultHandler", "onSetEndDateHandler", "onSetStartDateHandler"],
    "Table": ["handleSort", "onParamTypeChangeHandler"],
    "TableParameterBlock": ["onChangeSearchHandler", "onClearInputHandler", "onCloseSelectAppsModalHandler", "onCreateParamKeyHandler", "onOpenChangeParamKeyModalHandler", "onRepeatRequestHandler", "onScrollHandler"],
    "TableParamActionCell": ["onChangeSearchHandler", "onClearInputHandler", "onClickEditUndefinedHandler", "onClickTitleEditUndefinedModal", "onCloseSelectAppsModalHandler", "onDeleteParamKeyHandler", "onOpenChangeDeleteHandler", "onOpenChangeEditUndefinedModal", "onOpenChangeUpdateHandler"],
    "TableUserActionsCell": ["onDeleteUserHandler", "onOpenChangeDeleteHandler", "onOpenChangeUpdateHandler", "onUpdateUserHandler"],
    "TableUserBlock": ["onChangeHandler", "onGroupUsersDeleteHandler", "onOpenChangeDeleteHandler"],
    "TableVacationActionCell": ["onDeleteVacationHandler", "onOpenChangeEditHandler", "setOpenDelete", "setOpenEdit"],
    "TableVacationSettings": ["onCreateVacationNoteHandler", "onOpenChangeAddHandler", "setOpenAddVacation"],
    "TestActions": ["clickCommentHandler", "clickDeleteHandler", "clickLinksHandler", "clickViewHandler", "onToggleBar", "setIsCommentModalOpen", "setIsDeleteModalOpen", "setIsLinksModalOpen", "setIsOpenPopup", "setIsViewModalOpen"],
    "TestsFilters": ["onChangeFiltersHandler", "onResetAllFiltersHandler", "onResetFilterHandler", "setIsOpenFilterSelect"],
    "Textarea": ["handleInputValueChanged"],
    "TooltipComp": ["onOpenChangeHandler"],
    "TopAppsByKeyTable": ["onRepeatRequestHandler"],
    "TrafficKeyword": ["onCopyTitleHandler"],
    "TranslateText": ["onTranslateKeywordHandler"],
    "UpdateNiche": ["handleFormSubmitted", "onRepeatRequestHandler"],
    "UserCell": ["onChangeHandler"],
    "UserForm": ["handleFormSubmitted", "onRepeatRequestHandler", "onSubmitHandler"],
    "VacationForm": ["onBlurInputHandler", "onChangeInputHandler", "onChangeStepHandler", "onCloseCalendarHandler", "onKeyDownInputHandler", "onOpenCalendarHandler", "onSave", "onSetStartDateHandler"],
    "ValueBlock": ["onValueTypeChange"],
    "ViewModal": ["setIsViewModalOpen"]
}

module.exports = { SHARED_HANDLERS, HANDLER_NAME_PATTERN, WRONG_HANDLER_NAME_MESSAGE }
